wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
architecture:
  desc: null
  value: RegressionModel
batch_size:
  desc: null
  value: 128
dataset:
  desc: null
  value: adult
disable_dp:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.1
n_epoch:
  desc: null
  value: 20
sigma(noise):
  desc: null
  value: 0
