wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
architecture:
  desc: null
  value: RegressionModel
batch_size:
  desc: null
  value: 128
dataset:
  desc: null
  value: bank
disable_dp:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.1
n_epoch:
  desc: null
  value: 1
n_run:
  desc: null
  value: 0
run_name:
  desc: null
  value: test
sigma(noise):
  desc: null
  value: 1.0
